
services:
  frontend:
    build:
      context: ./crypto-tracking-app
    ports:
      - "3000:3000"
    volumes:
      - ./crypto-tracking-app:/app
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./crypto-tracking-api
    ports:
      - "4000:4000"
    env_file:
      - ./crypto-tracking-api/.env
    volumes:
      - ./crypto-tracking-api/src:/app/src
    command: npm run start:dev
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: